mod 'boxen', '3.6.1', :github_tarball => 'boxen/puppet-boxen'
mod 'git', '2.7.0', :github_tarball => 'boxen/puppet-git'
mod 'homebrew', '0.2.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'inifile',  '0.0.1', :github_tarball => 'boxen/puppet-inifile'
mod 'stdlib', '4.1.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
